Repository joelday/papyrus-lang, pull requests merged in 2019-11, with the labels that each got.

#93 CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  src/papyrus-lang-vscode/README.md
Labels: documentation

#96 Project File Generation
  appveyor.yml
  build.cake
  src/papyrus-lang-vscode/.gitignore
  src/papyrus-lang-vscode/package-lock.json
  src/papyrus-lang-vscode/package.json
  src/papyrus-lang-vscode/resources/fo4/Fallout4.code-workspace
  src/papyrus-lang-vscode/resources/fo4/fallout4.ppj
  src/papyrus-lang-vscode/resources/fo4/launch.json
  src/papyrus-lang-vscode/resources/fo4/tasks.json
  src/papyrus-lang-vscode/resources/sse/SkyrimSE.code-workspace
  src/papyrus-lang-vscode/resources/sse/launch.json
  src/papyrus-lang-vscode/resources/sse/skyrimse.ppj
  src/papyrus-lang-vscode/resources/sse/tasks.json
  src/papyrus-lang-vscode/src/CreationKitInfoProvider.ts
  src/papyrus-lang-vscode/src/ExtensionConfigProvider.ts
  src/papyrus-lang-vscode/src/PapyrusExtension.ts
  src/papyrus-lang-vscode/src/Paths.ts
  src/papyrus-lang-vscode/src/Utilities.ts
  src/papyrus-lang-vscode/src/debugger/DebugSupportInstallService.ts
  src/papyrus-lang-vscode/src/debugger/PapyrusDebugAdapterDescriptorFactory.ts
  src/papyrus-lang-vscode/src/features/CompilerTaskDefinition.ts
  src/papyrus-lang-vscode/src/features/CompilerTaskProvider.ts
  src/papyrus-lang-vscode/src/features/PyroTaskDefinition.ts
  src/papyrus-lang-vscode/src/features/PyroTaskProvider.ts
  src/papyrus-lang-vscode/src/features/commands/GenerateProjectCommand.ts
  src/papyrus-lang-vscode/src/features/commands/InstallDebugSupportCommand.ts
  src/papyrus-lang-vscode/src/server/LanguageClientHost.ts
  src/papyrus-lang-vscode/src/server/LanguageClientManager.ts
Labels: enhancement

#107 Issue #102: Support for SkyrimLE project file creation
  src/papyrus-lang-vscode/package.json
  src/papyrus-lang-vscode/resources/tesv/SkyrimLE.code-workspace
  src/papyrus-lang-vscode/resources/tesv/launch.json
  src/papyrus-lang-vscode/resources/tesv/skyrimle.ppj
  src/papyrus-lang-vscode/resources/tesv/tasks.json
  src/papyrus-lang-vscode/src/Utilities.ts
  src/papyrus-lang-vscode/src/features/commands/GenerateProjectCommand.ts
Labels: enhancement, skyrim le

#115 Fix nasty bug when no workspace open
  src/papyrus-lang-vscode/src/features/PyroTaskProvider.ts
Labels: bug

#118 docs: pull request templates and update CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/docs.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/refactor.md
  CONTRIBUTING.md
Labels: documentation

#119 docs: add default template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#120 docs: move default PR template to the .github meta folder
  .github/pull_request_template.md
Labels: documentation

#125 chore: Build all pull requests with Github CI
  .github/workflows/main.yml
Labels: workflow

#127 chore: Run github CI for master branch and pull request refs
  .github/workflows/main.yml
Labels: workflow

#121 refactor: Create IPathResolver service to simplify code that needs path information (#117)
  src/papyrus-lang-vscode/src/CreationKitInfoProvider.ts
  src/papyrus-lang-vscode/src/ExtensionConfigProvider.ts
  src/papyrus-lang-vscode/src/PapyrusExtension.ts
  src/papyrus-lang-vscode/src/PapyrusGame.ts
  src/papyrus-lang-vscode/src/Paths.ts
  src/papyrus-lang-vscode/src/Utilities.ts
  src/papyrus-lang-vscode/src/common/PathResolver.ts
  src/papyrus-lang-vscode/src/debugger/DebugSupportInstallService.ts
  src/papyrus-lang-vscode/src/debugger/PapyrusDebugAdapterDescriptorFactory.ts
  src/papyrus-lang-vscode/src/features/PyroTaskProvider.ts
  src/papyrus-lang-vscode/src/features/commands/GenerateProjectCommand.ts
  src/papyrus-lang-vscode/src/features/commands/ShowWelcomeCommand.ts
  src/papyrus-lang-vscode/src/server/LanguageClientHost.ts
  src/papyrus-lang-vscode/src/server/LanguageClientManager.ts
Labels: debugger, documentation, help wanted, language service, project explorer, pyro/build, refactoring, vscode extension

#122 feat: New pyro+bsarch and build task support for new pyro (#109)
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/docs.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/refactor.md
  .github/workflows/push-tag-rc.yml
  LICENSE
  README.md
  build.cake
  src/papyrus-lang-vscode/package-lock.json
  src/papyrus-lang-vscode/package.json
  src/papyrus-lang-vscode/resources/fo4/Fallout4.code-workspace
  src/papyrus-lang-vscode/resources/fo4/fallout4.ppj
  src/papyrus-lang-vscode/resources/sse/SkyrimSE.code-workspace
  src/papyrus-lang-vscode/resources/tesv/SkyrimLE.code-workspace
  src/papyrus-lang-vscode/resources/welcome/index.md
  src/papyrus-lang-vscode/src/PapyrusGame.ts
  src/papyrus-lang-vscode/src/Utilities.ts
  src/papyrus-lang-vscode/src/common/PathResolver.ts
  src/papyrus-lang-vscode/src/debugger/DebugSupportInstallService.ts
  src/papyrus-lang-vscode/src/features/PyroTaskDefinition.ts
  src/papyrus-lang-vscode/src/features/PyroTaskProvider.ts
  src/papyrus-lang-vscode/src/features/commands/GenerateProjectCommand.ts
Labels: enhancement, pyro/build, refactoring, vscode extension
